version: '3.8'

services:
  apm-alert:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apm-alert
    restart: always
    environment:
      - TZ=Asia/Tehran
      - ZONEINFO=/app/zoneinfo.zip

